
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.sullivan.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 47;
  public static final int STRING_LITERAL = 58;
  public static final int LBRACKET = 35;
  public static final int CHAR = 40;
  public static final int GREATER_EQ_THAN = 54;
  public static final int NOT_EQUAL = 57;
  public static final int INTEGER = 60;
  public static final int HASH = 29;
  public static final int INT = 39;
  public static final int MINUS = 46;
  public static final int FOR = 8;
  public static final int GREATER_THAN = 52;
  public static final int CHARACTER_LITERAL = 59;
  public static final int AND = 55;
  public static final int SEMICOLON = 18;
  public static final int RPAR = 15;
  public static final int OR = 56;
  public static final int BOOL = 41;
  public static final int COMMA = 17;
  public static final int ENDF = 4;
  public static final int ENDFOR = 9;
  public static final int PLUS = 45;
  public static final int ASSIGN = 19;
  public static final int MAIN = 2;
  public static final int IF = 5;
  public static final int AMPERSAND = 25;
  public static final int EXP = 31;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int DOUBLE_QUOTE = 22;
  public static final int EQUAL = 50;
  public static final int RBRACKET = 36;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int PIPE = 20;
  public static final int MOD = 49;
  public static final int LOWER_EQ_THAN = 53;
  public static final int VOID = 3;
  public static final int READLN = 10;
  public static final int SINGLE_QUOTE = 23;
  public static final int REAL = 61;
  public static final int TIMES = 48;
  public static final int COLON = 16;
  public static final int L_EXCL = 32;
  public static final int ENDIF = 6;
  public static final int LBRACE = 37;
  public static final int ELSE = 7;
  public static final int INV_DIAGONAL = 26;
  public static final int CLOSE_QMARK = 34;
  public static final int OP_QMARK = 33;
  public static final int DOLLAR = 27;
  public static final int FLOAT = 43;
  public static final int RBRACE = 38;
  public static final int LOWER_THAN = 51;
  public static final int UNDERSCORE = 28;
  public static final int STRING = 42;
  public static final int LPAR = 14;
  public static final int NEGATE = 24;
  public static final int AT = 30;
  public static final int FALSE = 13;
  public static final int PRINT = 11;
  public static final int IDENTIFIER = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "VOID",
  "ENDF",
  "IF",
  "ENDIF",
  "ELSE",
  "FOR",
  "ENDFOR",
  "READLN",
  "PRINT",
  "TRUE",
  "FALSE",
  "LPAR",
  "RPAR",
  "COLON",
  "COMMA",
  "SEMICOLON",
  "ASSIGN",
  "PIPE",
  "DOT",
  "DOUBLE_QUOTE",
  "SINGLE_QUOTE",
  "NEGATE",
  "AMPERSAND",
  "INV_DIAGONAL",
  "DOLLAR",
  "UNDERSCORE",
  "HASH",
  "AT",
  "EXP",
  "L_EXCL",
  "OP_QMARK",
  "CLOSE_QMARK",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "INT",
  "CHAR",
  "BOOL",
  "STRING",
  "FLOAT",
  "IDENTIFIER",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "TIMES",
  "MOD",
  "EQUAL",
  "LOWER_THAN",
  "GREATER_THAN",
  "LOWER_EQ_THAN",
  "GREATER_EQ_THAN",
  "AND",
  "OR",
  "NOT_EQUAL",
  "STRING_LITERAL",
  "CHARACTER_LITERAL",
  "INTEGER",
  "REAL"
  };
}

